name: Build and Push Docker Image

on:
  push:
    branches: [ main ]  # Adjust this to your primary branch name if needed
  workflow_dispatch:  # Allows manual triggering from GitHub UI

jobs:
  build-and-push:
    name: Build and Push Docker Image
    runs-on: ubuntu-latest
    
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3
      
      # Free up disk space
      - name: Free up disk space
        run: |
          echo "Listing top 20 largest packages before cleanup"
          sudo du -ha /usr/share | sort -rh | head -20
          
          echo "Removing unnecessary packages and cache"
          sudo rm -rf /usr/share/dotnet
          sudo rm -rf /usr/local/lib/android
          sudo rm -rf /opt/ghc
          sudo rm -rf /opt/hostedtoolcache
          
          echo "Removing Docker images not needed for this build"
          docker rmi $(docker images -aq) || true
          
          echo "Clearing Docker temporary build files"
          docker builder prune -af
          
          echo "Current disk space"
          df -h
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        with:
          driver-opts: |
            image=moby/buildkit:latest
            network=host
      
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      
      # Set up Docker layer caching
      - name: Set up Docker layer caching
        uses: actions/cache@v3
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-
      
      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/realtime-voice-chat:latest
            ${{ secrets.DOCKERHUB_USERNAME }}/realtime-voice-chat:${{ github.sha }}
          cache-from: |
            type=local,src=/tmp/.buildx-cache
            type=registry,ref=${{ secrets.DOCKERHUB_USERNAME }}/realtime-voice-chat:buildcache
          cache-to: |
            type=local,dest=/tmp/.buildx-cache-new,mode=max
            type=registry,ref=${{ secrets.DOCKERHUB_USERNAME }}/realtime-voice-chat:buildcache,mode=max
          platforms: linux/amd64
          # Add build arguments to improve caching and reduce size
          build-args: |
            BUILDKIT_INLINE_CACHE=1
          # Enable GitHub Actions advanced support for larger builds
          github-token: ${{ secrets.GITHUB_TOKEN }}
      
      # Move cache to avoid cache growing too large
      - name: Move cache
        run: |
          rm -rf /tmp/.buildx-cache
          mv /tmp/.buildx-cache-new /tmp/.buildx-cache 